services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: agenda_db
      POSTGRES_USER: agenda_user
      POSTGRES_PASSWORD: agenda_pass
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  web:
    build: .
    command: bash -lc '/app/entrypoint.sh web'
    env_file: .env
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  worker:
    build: .
    command: bash -lc '/app/entrypoint.sh worker'
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  beat:
    build: .
    command: bash -lc '/app/entrypoint.sh beat'
    env_file: .env
    depends_on:
      - worker
      - redis
      - db
    volumes:
      - .:/app

volumes:
  pgdata:
