services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: agenda_db
      POSTGRES_USER: agenda_user
      POSTGRES_PASSWORD: agenda_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agenda_user -d agenda_db -h localhost"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    restart: unless-stopped

  web:
    build: .
    command: bash -lc '/app/entrypoint.sh web'
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8001:8000"    # <— mudou aqui (host:container)
    volumes:
      - .:/app
    restart: unless-stopped

  worker:
    build: .
    command: bash -lc '/app/entrypoint.sh worker'
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    restart: unless-stopped

  beat:
    build: .
    command: bash -lc '/app/entrypoint.sh beat'
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  pgdata:
