# Generated by Django 5.2.6 on 2025-10-06 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reminder',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end__gte', models.F('start'))), name='event_end_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.UniqueConstraint(fields=('event', 'minutes_before', 'channel'), name='uniq_reminder_event_minutes_channel'),
        ),
    ]
